### ISSUE TITLE
Issue from List

### ISSUE THREAD

**Issue by vsoch** [Singularity-tutorial/Singularity-tutorial.github.io#1]
This is from a user on the Singularity List:

>> I'm trying to deploy Singularity on our Linux cluster, and as an initial test I run the tutorial in https://singularity-tutorial.github.io/ 

>> The tutorial instructions fail, however, when I try to build the lolcow container in a normal user's home directory: 
```
$ sudo singularity build --sandbox lolcow Singularity 
[sudo] password for XXX: 
Building into existing container: lolcow 
Using container recipe deffile: Singularity 
tar: .: Cannot utime: Permission denied 
tar: .: Cannot change ownership to uid 0, gid 0: Operation not permitted 
tar: Exiting with failure status due to previous errors 
ERROR: Failed to export contents of Singularity to lolcow 
ABORT: Aborting with RETVAL=255 
Cleaning up... 
```
>> The reason is very obvious: User home directories are NFS mounted without root permissions to the NFS clients (and obviously so, I'd say!). 

>> Request: Please update the tutorial homepage by explicitly instructing users to build containers on a locally mounted storage, for example /tmp. 

>> Request for enhancement: The "singularity build" command should check for root access to the current working directory, and exit with a nice and informative message if this condition is not fulfilled. 

Thanks!

**Comment by GodloveD** [comment]
Hiya @OleHolmNielsen!  Thanks for the feedback.  (And thanks @vsoch for conveying the feedback. 😄 ).  

When I teach this workshop, I usually have VMs set up for all of the participants.  So the examples are meant to work on AWS or GCP VMs where the users have root.  I could add a disclaimer line to tell users that the build commands will not work on an NFS system that is mounted with root squash, but the class is really geared toward people who may have very limited Linux experience and I don't want to muddy the waters by talking about features that they have probably never heard of and that probably don't have anything to do with them if they are running the examples on a VM or personal machine.  

However, I think your second suggestion is a great idea!  Singularity should totally give an informative error message when it can't write to the location requested.  I'm going to raise an issue on the [singularity repo](https://github.com/singularityware/singularity/issues) so that we can keep track of this and make sure it gets done.

**Comment by OleHolmNielsen** [comment]
Hi David,
I was excited to follow your tutorial at SC17, and now I'm testing the tutorial user experience on our Linux cluster, since your tutorial is a great way for users to get started with Singularity.
However, chances are that many people trying out your tutorial will do so in a home directory on a shared NFS file server. Can you imagine the user frustrations when "singularity build" crashes as shown above, and they don't have a clue why? 
I would propose to add under the "Building a basic container" heading a text like:
"You need to build containers on a file system where the sudo command can write files as root. This may not work if your home directory resides on a shared file server, so it's recommended to change directory a local hard disk such as the /tmp directory: cd /tmp; mkdir lolcow"
I'm glad that you agree that "singularity build" should give a more informative error message when it can't write files as root.
/Ole

**Comment by GodloveD** [comment]
OK.  You convinced me @OleHolmNielsen I added the appropriate note.  Thanks!
