### ISSUE TITLE
Unable to build container with changes from sandbox

### ISSUE THREAD

**Issue by jwscook** [Singularity-tutorial/Singularity-tutorial.github.io#4]
Hi,

I've very much enjoyed following this tutorial, but I have run into some trouble. It's worth noting that I'm running `singularity version 3.0.2-365.g3ad56a21`, which could be the reason?

Where it says `Here is what our updated definition file should look like.` in the tutorial, I find that the definition file has not changed. Can you advise what I should do to save the changes made in the `--writable` session?

Thanks,
James

**Comment by GodloveD** [comment]
Hi @jwscook 👋.  This tutorial really needs to be updated to v3.0.3!  But I don't think that has anything to do with this issue.  

I should be more clear.  The definition file does not automatically change.  You have to update it manually.  The basic idea behind this suggested development flow is that you will make changes to your container in `--writable` mode.  Then as you make changes you will keep notes about what you did.  Ultimately, those notes will become your updated definition file and you will use it to create an immutable, production-ready container.  

Maybe you could suggest a way to make this idea more clear so that others do not have the same confusion?

**Comment by jwscook** [comment]
Ahh. I thought it would magically do that for me 😆. It actually does say `Let's update our definition file with the changes we made  to this container`!

I had a preconception of what was supposed to happen and didnt challenge it in the face of evidence. I don't think there any changes to the tutorial that can combat that!

**Comment by GodloveD** [comment]
I've _finally_ gotten around to updating this tutorial.  😄 

https://github.com/Singularity-tutorial/Singularity-tutorial.github.io/pull/5
